variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  HEROKU_API_KEY: "487d96d2-48c0-4b44-88d4-05398c728bb0"
  HEROKU_APP_NAME: "wgu-visionvault-server"
  DOCKER_IMAGE_NAME: "visionvault"

services:
  - docker:dind

stages:
  - build
  - package
  - deploy

build:
  image: maven:3.8.1-openjdk-17-slim
  stage: build
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar

package:
  image: docker:20.10.7
  stage: package
  before_script:
    - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
  script:
    - ls -la target/
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker tag $DOCKER_IMAGE_NAME registry.heroku.com/$HEROKU_APP_NAME/web
    - docker push registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  image: alpine:3.14
  stage: deploy
  script:
    - apk add --no-cache curl bash nodejs
    - curl https://cli-assets.heroku.com/install.sh | bash
    - heroku container:release web -a $HEROKU_APP_NAME
  only:
    - deployment

